# Site settings
title1: "EMNLP 16 Workshop "
title2: "Structured Prediction for Natural Language Processing"
email: kw@kwchang.net
#description: "EMNLP 16: Structured Prediction for Natural Language Processing"
baseurl: ""
url1: "http://www.emnlp2016.net"
url2: "http://structuredprediction.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
